from .infrastructure import COMPONENTS as INFRASTRUCTURE_COMPONENTS
from .observability import COMPONENTS as OBSERVABILITY_COMPONENTS
from .runtime import COMPONENTS as RUNTIME_COMPONENTS
from .workflow import COMPONENTS as WORKFLOW_COMPONENTS

ALL_COMPONENTS = [
    *INFRASTRUCTURE_COMPONENTS,
    *OBSERVABILITY_COMPONENTS,
    *RUNTIME_COMPONENTS,
    *WORKFLOW_COMPONENTS,
]
